services:
  app:
    container_name: bmg-shop-app
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NODE_VERSION: 20
    env_file:
      - docker/env/.env.develop
    environment:
      NODE_ENV: "production"
      TZ: "Asia/Ho_Chi_Minh"
      PORT: "8000"
      # 👉 URL này là Neon Cloud DB
      DATABASE_URL: "postgresql://neondb_owner:npg_oUs8lLVi1cWv@ep-silent-mode-a1zbfikm-pooler.ap-southeast-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require"
      POSTGRES_DB: neondb
      POSTGRES_USER: neondb_owner
      POSTGRES_PASSWORD: npg_oUs8lLVi1cWv
    ports:
      - "8000:8000"
    restart: unless-stopped
    command: ["node", "dist/server.js"]
