version: '3.3'
services:
  app:
    container_name: heyotrip-app
    build: .
    ports:
      - 3000:3000
    environment:
      DB_USER: ${DB_USER:-neondb_owner}
      DB_PASSWORD: ${DB_PASSWORD:-npg_oUs8lLVi1cWv}
      DB_HOST: ${DB_HOST:-ep-silent-mode-a1zbfikm-pooler.ap-southeast-1.aws.neon.tech}
      DB_PORT: ${DB_PORT:-5432}
      DB_NAME: ${DB_NAME:-neondb}
      DB_SSL: ${DB_SSL:-true}
