version: '3.8'
services:
  app:
    container_name: bmg-shop
    build: .
    env_file: .env
    expose:
      - "5000"              # nội bộ cho nginx
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://127.0.0.1:5000/health"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 20s
    volumes:
      - ./logs:/app/logs

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "80:80"             # public HTTP
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - app
    restart: unless-stopped