version: '3.8'

services:
  app:
    container_name: bmg-shop
    build: .
    ports:
      - "${PORT:-5000}:5000"
    env_file:
      - .env
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://127.0.0.1:5000/health"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 20s
    volumes:
      - ./logs:/app/logs